include package/qt5/qtbase/qtbase.mk
include package/qt5/qtxmlpatterns/qtxmlpatterns.mk
include package/qt5/qtjsbackend/qtjsbackend.mk
include package/qt5/qtdeclarative/qtdeclarative.mk
include package/qt5/qtmultimedia/qtmultimedia.mk
include package/qt5/qtwayland/qtwayland.mk
include package/qt5/qtgraphicaleffects/qtgraphicaleffects.mk
include package/qt5/qtwebkit/qtwebkit.mk
include package/qt5/qtimageformats/qtimageformats.mk
include package/qt5/qtquick1/qtquick1.mk
include package/qt5/qtscript/qtscript.mk
include package/qt5/qtsvg/qtsvg.mk
include package/qt5/qt3d/qt3d.mk
include package/qt5/qtgamepad/qtgamepad.mk
