XPROTO_VERSION = 7.0.23
XPROTO_SITE = http://www.x.org/releases/X11R7.7/src/proto
XPROTO_SOURCE = xproto-$(XPROTO_VERSION).tar.gz
XPROTO_DEPENDENCIES = 
XPROTO_INSTALL_STAGING = YES

#XPROTO_CONF_OPT += 
#XPROTO_AUTORECONF = YES

$(eval $(autotools-package))