XKBCOMMON_VERSION = 0.2.0
XKBCOMMON_SITE = http://xkbcommon.org/download
XKBCOMMON_SOURCE = libxkbcommon-$(XKBCOMMON_VERSION).tar.bz2
XKBCOMMON_DEPENDENCIES = 
XKBCOMMON_INSTALL_STAGING = YES

#XKBCOMMON_CONF_OPT += 
#XKBCOMMON_AUTORECONF = YES

$(eval $(autotools-package))